- name: Ensure dependencies are installed
  become: true
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
    update_cache: true
  loop:
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - libffi-dev
    - liblzma-dev
    - git

- name: Clone pyenv/pyenv
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/.pyenv
    version: master

- name: Place .bashrc config
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    marker: "# pyenv {mark} ANSIBLE MANAGED BLOCK"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      cd ${HOME}/.pyenv/ && git pull && cd -
      if command -v pyenv 1>/dev/null 2>&1; then
        eval "$(pyenv init --path)"
      fi

- name: Install python, enable pip
  ansible.builtin.shell: |
    eval "$(pyenv init --path)"
    pyenv install {{ pyenv_python_version }}
    pyenv global {{ pyenv_python_version }}
