- name: Add aliases to bashrc
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    block: |
      function zload() {
        sudo zfs load-key -L prompt $1 && sudo zfs mount $1
      }
      function zunload() {
        sudo zfs unmount -f $1 && sudo zfs unload-key $1
      }

